# WeChat Pay
wechat:
  id: please fill in with mini program app id
  secret: please fill in with mini program app secret
  session:
    url: https://api.weixin.qq.com/sns/jscode2session
    grant-type: authorization_code
  pay:
    url: https://api.mch.weixin.qq.com/pay/unifiedorder
    notify: please fill in with wechat pay notify url
    type: JSAPI
    mch-id: please fill in with wechat pay mch id
    key: please fill in with wechat pay api key